### ISSUE TITLE
ValueError: Buffer dtype mismatch, expected 'int' but got 'long'

### ISSUE THREAD

**Issue by hroncok** [bimboslaff/wator#1]
When I click "Next chronon":

```
Traceback (most recent call last):
  File ".../wator/wator/gui.py", line 127, in tick_button_clicked
    grid.wator.tick()
  File ".../wator/wator/wator.py", line 78, in tick
    self.energy_eat)
  File "wator/speedup.pyx", line 16, in speedup.move_animals
    move_fish(row, column, creatures[row, column], processed_squares, creatures, energies, fish_reproduce)
  File "wator/speedup.pyx", line 88, in speedup.move_fish
    cdef move_fish(int row, int column, int value, processed_squares,
ValueError: Buffer dtype mismatch, expected 'int' but got 'long'
```

**Comment by bimboslaff** [comment]
@hroncok Works on my machine.... I assume you used your file to test WaTor? Could you share it with me?

**Comment by hroncok** [comment]
No file. Just added some creatures in the editor and hit the button. I run Linux, 64bit.

**Comment by bimboslaff** [comment]
Could you try now?

**Comment by hroncok** [comment]
Fixed.
